github: [Custura]
website: [custura.de, zaimea.com, groups.zaimea.com, accounts.zaimea.com]
facebook: [zaimeacom]
instagram: [zaimeacom]
x: [zaimeacom]
youtube: [Custura.Laurentiu]

custom: ['hosted': '$2y$12$95iV8lmbIfpzNGMws9.UuO0cNCbH.IyfVfZPKNEfqec3SJ1cNE/dS']
